trial_objects = [
    {
        "stimulus": "audio/NL/NL_01_N.mp3",
        "clip": "NL_01_N",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NL/NL_01_L.mp3",
        "clip": "NL_01_L",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NL/NL_02_N.mp3",
        "clip": "NL_02_N",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NL/NL_02_L.mp3",
        "clip": "NL_02_L",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NL/NL_03_N.mp3",
        "clip": "NL_03_N",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NL/NL_03_L.mp3",
        "clip": "NL_03_L",
        "gender": "M",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NL/NL_04_N.mp3",
        "clip": "NL_04_N",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NL/NL_04_L.mp3",
        "clip": "NL_04_L",
        "gender": "M",
        "condition": "lazy",
    },
    # // {
    # //     "stimulus": "audio/NL/NL_05_N.mp3",
    # //     "clip": "NL_05_N",
    # //     "gender": "M",
    # //     "condition": "proper",
    # // },
    # // {
    # //     "stimulus": "audio/NL/NL_05_L.mp3",
    # //     "clip": "NL_05_L",
    # //     "gender": "M",
    # //     "condition": "lazy",
    # // },
    {
        "stimulus": "audio/NL/NL_06_N.mp3",
        "clip": "NL_06_N",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NL/NL_06_L.mp3",
        "clip": "NL_06_L",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NL/NL_07_N.mp3",
        "clip": "NL_07_N",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NL/NL_07_L.mp3",
        "clip": "NL_07_L",
        "gender": "M",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NL/NL_08_N.mp3",
        "clip": "NL_08_N",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NL/NL_08_L.mp3",
        "clip": "NL_08_L",
        "gender": "M",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NL/NL_09_N.mp3",
        "clip": "NL_09_N",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NL/NL_09_L.mp3",
        "clip": "NL_09_L",
        "gender": "M",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NL/NL_10_N.mp3",
        "clip": "NL_10_N",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NL/NL_10_L.mp3",
        "clip": "NL_10_L",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGG/NGG_01_NG.mp3",
        "clip": "NGG_01_NG",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGG/NGG_01_G.mp3",
        "clip": "NGG_01_G",
        "gender": "M",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGG/NGG_02_NG.mp3",
        "clip": "NGG_02_NG",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGG/NGG_02_G.mp3",
        "clip": "NGG_02_G",
        "gender": "M",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGG/NGG_03_NG.mp3",
        "clip": "NGG_03_NG",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGG/NGG_03_G.mp3",
        "clip": "NGG_03_G",
        "gender": "M",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGG/NGG_04_NG.mp3",
        "clip": "NGG_04_NG",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGG/NGG_04_G.mp3",
        "clip": "NGG_04_G",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGG/NGG_05_NG.mp3",
        "clip": "NGG_05_NG",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGG/NGG_05_G.mp3",
        "clip": "NGG_05_G",
        "gender": "M",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGG/NGG_06_NG.mp3",
        "clip": "NGG_06_NG",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGG/NGG_06_G.mp3",
        "clip": "NGG_06_G",
        "gender": "M",
        "condition": "lazy",
    },
    # // {
    # //     "stimulus": "audio/NGG/NGG_07_NG.mp3",
    # //     "clip": "NGG_07_NG",
    # //     "gender": "M",
    # //     "condition": "proper",
    # // },
    # // {
    # //     "stimulus": "audio/NGG/NGG_07_G.mp3",
    # //     "clip": "NGG_07_G",
    # //     "gender": "M",
    # //     "condition": "lazy",
    # // },
    {
        "stimulus": "audio/NGG/NGG_08_NG.mp3",
        "clip": "NGG_08_NG",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGG/NGG_08_G.mp3",
        "clip": "NGG_08_G",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGG/NGG_09_NG.mp3",
        "clip": "NGG_09_NG",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGG/NGG_09_G.mp3",
        "clip": "NGG_09_G",
        "gender": "M",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGG/NGG_10_NG.mp3",
        "clip": "NGG_10_NG",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGG/NGG_10_G.mp3",
        "clip": "NGG_10_G",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGN/NGN_01_NG.mp3",
        "clip": "NGN_01_NG",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGN/NGN_01_N.mp3",
        "clip": "NGN_01_N",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGN/NGN_02_NG.mp3",
        "clip": "NGN_02_NG",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGN/NGN_02_N.mp3",
        "clip": "NGN_02_N",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGN/NGN_03_NG.mp3",
        "clip": "NGN_03_NG",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGN/NGN_03_N.mp3",
        "clip": "NGN_03_N",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGN/NGN_04_NG.mp3",
        "clip": "NGN_04_NG",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGN/NGN_04_N.mp3",
        "clip": "NGN_04_N",
        "gender": "M",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGN/NGN_05_NG.mp3",
        "clip": "NGN_05_NG",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGN/NGN_05_N.mp3",
        "clip": "NGN_05_N",
        "gender": "M",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGN/NGN_07_NG.mp3",
        "clip": "NGN_07_NG",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGN/NGN_07_N.mp3",
        "clip": "NGN_07_N",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGN/NGN_08_NG.mp3",
        "clip": "NGN_08_NG",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGN/NGN_08_N.mp3",
        "clip": "NGN_08_N",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGN/NGN_09_NG.mp3",
        "clip": "NGN_09_NG",
        "gender": "F",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGN/NGN_09_N.mp3",
        "clip": "NGN_09_N",
        "gender": "F",
        "condition": "lazy",
    },
    {
        "stimulus": "audio/NGN/NGN_10_NG.mp3",
        "clip": "NGN_10_NG",
        "gender": "M",
        "condition": "proper",
    },
    {
        "stimulus": "audio/NGN/NGN_10_N.mp3",
        "clip": "NGN_10_N",
        "gender": "M",
        "condition": "lazy",
    }
]
